name: pgbee
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.5
  google_sign_in: ^7.1.1
  dio: ^5.8.0+1

dev_dependencies:
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets of Application
  assets:
    - assets/images/PgBee.svg
    - assets/images/logo.png

  # To add fonts of Application
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

